### PR TITLE
Use Go Modules 

### PR DESCRIPTION
**Pull request by iwittkau**
- initialize go modules config
- update travis settings to use latest go version

### CODE REVIEW

**Comment by iwittkau** [comment]
@eduncan911 I saw you preparing a new release. Maybe it is a good time to introduce go modules to the project?

**Comment by eduncan911** [comment]
Honestly, I've been removed from Go development for a few years and need to read up on Go Modules.

But I agree, it's the way to go.  I just need to make sure this PR fits with my development methodology (able to develop locally, without internet access).

**Comment by eduncan911** [comment]
What does Go Modules buy us over the `/vendor` folder?

**Comment by iwittkau** [comment]
> But I agree, it's the way to go. I just need to make sure this PR fits with my development methodology (able to develop locally, without internet access).

Should be no problem if you have downloaded the dependencies. You only need internet access if you want to update dependencies. So this should work as before.

> What does Go Modules buy us over the `/vendor` folder that already has the deps?

The folder can be removed entirely because the dependencies are locked in the `go.mod` and `go.sum` files.

Also, using Go modules ensures compatibility to other projects importing your project.

**Comment by eduncan911** [comment]
Ok, I read something on the Internet on go modules and I am now an expert.  /s

> Should be no problem if you have downloaded the dependencies.

Which is problem 1.  Some of workflows involve distributed tarballs on disconnected VMs and labs (think pin testing and virus debugging).  Though it's a stretch to say this Podcast repo would be affected by that, there are other Go tools I use that would directly affected by " if you have downloaded the dependencies."  So yes, this violates my workflows across all of my projects since it is not pre-packaged.

> The folder can be removed entirely

Which is problem 2, see above 1.  I prefer to have a distribution package that includes all dependencies, which with Golang, means a `/vendor` folder.

The good news is I see that `go mod` supports the creation of, and updating of, the `/vendor` folder.  (though Go Modules themselves ignore vendor folders when in `module` mode, according to the docs).  

So yes, i can see the benefit of including `go mod` in this PR!

However, I use SEMVER in this repo.  Which means I guaranteed backward compatibility with the 1.x branch (I've updated the docs in the `develop` repo, which will be in the README and release notes soon when I release).  `go mod` is only supported on 1.13 (1.11/1.12 experimental support).  This would break older installs that are not running on 1.13.

With that said, having go modules support the `/vender` folder would negate that, as older runtimes should continue to work.

So... Here's the way forward with this PR...

* Has the potential for a breaking change, which means it may need to be delayed until the 2.x branch is ready - or extensive testing is performed (see next bullet point).
* I am finally getting around to adding Github Actions to this repo, to replace travis.  With it, I can setup parallel builds that will build and test under multiple `go` runtimes - including the 1.6 version that this 1.x branch was originally released under to guarantee support.

If the latter proves it works flawlessly under 1.6 and above, then I can earmark this for a 1.4.x release (not the new 1.3.2 I am working on right now to release).  However, if something breaks in the CI for older versions/runtimes, then it will have to be deferred to a 2.x release.

Make sense?

So yeah, let's keep this PR open.  Btw, I am getting rid of the `develop` branch here as gitflow is not really needed.  This doesn't affect this PR; however, it limits my ability to merge this PR and test it out - since it lives in your fork.  **Would you mind granting me access to your forked repo?**  I may add the github actions there.  Either that, or make a new PR against the `develop` branch so i can test things there after I merge.

**Comment by eduncan911** [comment]
Ok, fixed up the develop branch and got it back inline.

Edited this PR to go against the `develop` branch,

But now, there are a few conflicts...  Sorry about that.

I recommend rebasing, not merging, from the develop branch back to yours.

**Comment by eduncan911** [comment]
Merged this in with #25, so closing this particular PR.

Thank you!

**Comment by iwittkau** [comment]
@eduncan911 nice! And also **thank you** four this library!

**Comment by eduncan911** [comment]
No problem.  I need to finish my blog about this minimalist testing strategy that yields 100% coverage.  "Minimalist" as in, low effort vs high coverage.

It's why I wrote this library - to demonstrate the patterns in a single example.

---

Btw, I'd love to hear how it's being used on your side.

**Comment by iwittkau** [comment]
I want to build a podacast hosting service for self-hosting. But I don't have anything to show off atm. 
In general it just makes me happy that this library exists because it is good to have open accessible stuff in the podcasting ecosystem.

**Pull request closed without merging**
